version: '3.8'

services:
  api:
    build: .
    container_name: superman-api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - kafka
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  streamlit:
    build:
      context: .
    container_name: superman-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    command: streamlit run monitoring/dashboard.py --server.port=8501 --server.address=0.0.0.0

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
